name: Deploy to EC2
on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_USER: ${{ secrets.SSH_USERNAME }}
  REMOTE_HOST: ${{ secrets.SSH_HOST }}
  APP_NAME: ${{ secrets.APP_NAME }}
  APP_DIR: ${{ secrets.EC2_DIR }}
  APP_PORT: 8080
  NODE_ENV: production
  # DATABASE VARIABLES
  DB_HOST: ${{ secrets.DATABASE_HOST }}
  DB_PORT: ${{ secrets.DATABASE_PORT }}
  DB_USER: ${{ secrets.DATABASE_USER }}
  DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DB_NAME: ${{ secrets.DATABASE_NAME }}
  # SMTP VARIABLE   
  SMTP_HOST: ${{ secrets.SMTP_HOST }}
  SMTP_PORT: ${{ secrets.SMTP_PORT }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PASS: ${{ secrets.SMTP_PASS }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create .env file
        run: |
          touch .env
          echo APP_NAME="$APP_NAME" >> .env
          echo APP_URL="$APP_URL" >> .env
          echo APP_PORT="$APP_PORT" >> .env
          
          echo CLIENT_URL="$CLIENT_URL" >> .env
          
          echo DB_HOST="$DB_HOST" >> .env
          echo DB_PORT="$DB_PORT" >> .env
          echo DB_USER="$DB_USER" >> .env
          echo DB_PASSWORD="$DB_PASSWORD" >> .env
          echo DB_NAME="$DB_NAME" >> .env
          
          echo JWT_SECRET="$JWT_SECRET" >> .env
          
          echo SMTP_HOST="$SMTP_HOST" >> .env
          echo SMTP_PORT="$SMTP_PORT" >> .env
          echo SMTP_USER="$SMTP_USER" >> .env
          echo SMTP_PASS="$SMTP_PASS" >> .env
          
          echo "cat .env"
          cat .env
          echo "ls -a ."
          ls -a .

          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          APP_NAME: ${{ secrets.APP_NAME }}
          APP_DIR: ${{ secrets.EC2_DIR }}
          APP_PORT: 8080
          NODE_ENV: production
          # DATABASE VARIABLES
          DB_HOST: ${{ secrets.DATABASE_HOST }}
          DB_PORT: ${{ secrets.DATABASE_PORT }}
          DB_USER: ${{ secrets.DATABASE_USER }}
          DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DB_NAME: ${{ secrets.DATABASE_NAME }}
          # SMTP VARIABLE   
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
      
      - name: Install dependencies
        run: npm ci --include=dev


      - name: Build TypeScript code
        run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          key: ${{ env.SSH_PRIVATE_KEY }}
          username: ${{ env.SSH_USERNAME }}
          host: ${{ env.SSH_HOST }}
          source: ./
          target: /home/ec2-user/${{ env.APP_DIR }}
          exclude: /node_modules/, /src/, /.git/, /.github/, .gitignore, README.md
          script_after: |
            cd /home/ec2-user/${{ env.APP_DIR }}
            npm install --production
            npm run migrate
            sudo pm2 restart app
