name: Deploy to EC2
on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_USER: ${{ secrets.SSH_USERNAME }}
  REMOTE_HOST: ${{ secrets.SSH_HOST }}
  APP_NAME: ${{ secrets.APP_NAME }}
  APP_PORT: 8080
  NODE_ENV: production
  # DATABASE VARIABLES
  DB_HOST: ${{ secrets.DATABASE_HOST }}
  DB_PORT: ${{ secrets.DATABASE_PORT }}
  DB_USER: ${{ secrets.DATABASE_USER }}
  DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DB_NAME: ${{ secrets.DATABASE_NAME }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci --include=dev


      - name: Build TypeScript code
        run: npm run build

      - name: Copy files to server
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          key: ${{ env.SSH_PRIVATE_KEY }}
          username: ${{ env.SSH_USERNAME }}
          host: ${{ env.SSH_HOST }}
          source: ./
          target: /home/ec2-user/${{ env.APP_NAME }}
          exclude: /node_modules/, /src/, /.git/, /.github/, .gitignore, README.md
          script_after: |
            cd /home/ec2-user/${{ env.APP_NAME }}
            npm install --production
            npm run migrate
            sudo pm2 restart app
